navbar:
  title: "麻田 真弘"
  type: default
  left:
    - text: "Home"
      href: index.html
    - text: "Research"
      href: Syllabus.html
    - text: "Mannfred"
      menu:
      - text: "About"
        href: about.html
      - text: "Contact"
        href: contact.html
      - text: "Fun"
        href: fun.html

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-minimal