---
title: "<span style='font-size: 20px'>research</style>"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Finished stuff on [google scholar](https://scholar.google.com/citations?user=wq79h-AAAAAJ&hl=en)(feel free to [email me](./contact.html) for .pdfs!)\

\
\

Ongoing projects:\

`curvr`: an `R` package for measuring total curvature from landmarked specimens. This package implements the concepts and definitions of point-wise and total curvature as described in [Boehm et al 2021](./cv.html)\

Bill morphology as a driver or consequence of niche partitioning in Neotropical hummingbirds: This project is in collaboration with [Juan Luis Parra](https://sites.google.com/view/juanluisparra/home) at Universidad de Antioquia, Colombia. By quantifying bill morphology and environment across communities of Neotropical hummingbirds, we are working to disentangle the biotic and abiotic drivers of phylogenetic community structure in this clade of rapidly diversifying family of vertebrates.\


